Fbs 35
flow-build/studio pull request #100
Opened 2023-05-19 17:38 UTC by BalanFC

2023-05-22 15:10 UTC, danilopessoa requested changes

2023-05-22 15:10 UTC, danilopessoa commented on src/pages/diagram/dialogs/edit-diagram/edit-diagram.tsx
>      updateDiagramSuccess(diagramName);
Dentro desse `updateDiagramSuccess` não poderia passar direto o `diagram.payload.name`?

2023-05-22 15:10 UTC, danilopessoa commented on src/pages/diagram/dialogs/save-diagram/save-diagram.tsx
> +    const diagramName = diagram.payload.name;
Declarado mas não está sendo usado?

2023-05-22 18:33 UTC, elsonfojr-fdte requested changes

2023-05-22 18:33 UTC, elsonfojr-fdte commented on src/shared/components/checkbox/styles.ts
> +export const Container = styled(FormGroup)``;
O padrão que está sendo utilizado no projeto é de Wrapper ser o nome do component que engloba todos os outros elementos. Inverter o Container com Wrapper. Além disso, o faz mais sentido nomear o Container de Checkbox ou CheckboxControl por exemplo

```suggestion
export const Wrapper = styled(FormGroup)``;

export const CheckboxControl = styled(Checkbox)``;
```

2023-05-22 18:33 UTC, elsonfojr-fdte commented on src/shared/components/checkbox/checkbox.tsx
> +    </S.Container>
Alterar o nome dos component para seguir o padrão utilizado no projeto:

```suggestion
    <S.Wrapper>
      <S.Label control={<S.CheckboxControl {...props} />} label={props["aria-label"]} />
    </S.Wrapper>
```

2023-05-22 18:33 UTC, elsonfojr-fdte commented on src/pages/diagram/dialogs/edit-diagram/edit-diagram.tsx
>  export const EditDiagram: React.FC<Props> = ({ isOpen, onClose, id }) => {
Já que este component será utilizado tanto para criar um diagrama novo quanto para editar um diagrama já existente, seria mais interessante alterar o nome. Exemplo: EditDiagram para FormDiagram.

Obs.: a sugestão de nome foi feita apenas para exemplificar, fique a vontade pra pensar em um outro nome :)

```suggestion
export const FormDiagram: React.FC<Props> = ({ isOpen, onClose, id }) => {

```

2023-05-22 18:33 UTC, elsonfojr-fdte commented on src/pages/diagram/dialogs/diagram-confirmation/diagram-confirmation.tsx
> +      dispatch(setEditDialog({ isVisible: true }));
Como o component servirá tanto para salvar quanto para editar, trocar o nome da função. (Pode ser o mesmo padrão do nome escolhido para o component)

```suggestion
      dispatch(setFormDialog({ isVisible: true }));

```

2023-05-22 18:33 UTC, elsonfojr-fdte commented on src/pages/diagram/diagram.tsx
>          <S.EditDiagramDialog
Alterar o nome do component para o escolhido no component novo do formulario de diagrama.

2023-05-23 12:11 UTC, elsonfojr-fdte approved these changes

2023-05-23 12:32 UTC, danilopessoa approved these changes

2023-05-23 12:38 UTC, merged