Feat/fs 227 create table workflows
flow-build/studio pull request #108
Opened 2023-06-20 20:49 UTC by BalanFC

2023-06-20 21:09 UTC, danilopessoa commented on src/pages/workflows/index.tsx
> +    </>
Não é necessário esse react fragment aqui.

2023-06-20 21:11 UTC, danilopessoa requested changes

2023-06-20 21:11 UTC, danilopessoa commented on src/pages/workflows/index.tsx
> +    </>
Não é necessário esse react fragment aqui.

2023-06-21 12:43 UTC, elsonfojr-fdte requested changes

2023-06-21 12:43 UTC, elsonfojr-fdte commented on src/interfaces/index.ts
> +}
Para seguir o padrão dos outros arquivos, move esses types para dentro da pasta workflowPageTypes.

_src/interfaces/workflowPage/index.ts_

2023-06-21 12:43 UTC, elsonfojr-fdte commented on src/styles/workflowPageStyles/index.ts
> +  margin-top: 2rem;
Utilizar a contante _spacing_ exportada lá do theme.

```suggestion
  margin-top: ${spacing.S32};
```

2023-06-21 12:43 UTC, elsonfojr-fdte commented on src/pages/workflows/index.tsx
> +        <Table column={column} rowData={data} onRowClick={Logger.info} paginable />
Acredito não haver necessidade de utilizar onRowClick

```suggestion
        <Table column={column} rowData={data} paginable />
```

2023-06-21 12:43 UTC, elsonfojr-fdte commented on src/pages/workflows/index.tsx
> +  }, []);
Acredito que a melhor abordagem neste caso seria utilizar getServerSideProps ao invés de useEffect. Com o getServerSideProps você pode fazer verificações de usuário autenticado (redirecionando para outra tela caso não esteja) e se o usuário fez as configurações necessárias. Dessa forma garante que esses pré requisitos foram atendidos antes de acessar a tela

2023-06-21 12:46 UTC, BalanFC commented on src/interfaces/index.ts
> +}
Poutz, tinha esquecido

2023-06-21 13:58 UTC, elsonfojr-fdte approved these changes

2023-06-21 14:34 UTC, danilopessoa approved these changes

2023-06-21 18:52 UTC, closed without merging