[FS-256]
flow-build/studio pull request #112
Opened 2023-06-27 11:07 UTC by elsonfojr-fdte

2023-06-27 13:01 UTC, danilopessoa requested changes

2023-06-27 13:01 UTC, danilopessoa commented on src/features/settings/FlowbuildServer/index.tsx
> +  const portRef = useRef<TextFieldProps>(null);
`TextFieldProps` não aceita null como valor, talvez seja interessante iniciar sem nenhuma informação, assim evita warnings de lint.

2023-06-27 13:01 UTC, danilopessoa commented on src/features/settings/FlowbuildServer/index.tsx
> +    const tokenResponse = await createToken(userId);
O método `getUserId` pode retornar `undefined`, mas o método `createToken` não espera `undefined` como um possível valor de `userId`, talvez seja legal fazer um tratamento ai.

2023-06-27 13:36 UTC, BalanFC approved these changes

2023-06-28 16:43 UTC, danilopessoa approved these changes

2023-06-28 17:21 UTC, merged