[Fbs 36] - Integrar dashboard de processos
flow-build/studio pull request #29
Opened 2022-08-18 13:58 UTC by gabrielacsalesc

2022-08-23 12:26 UTC, gabrielacsalesc commented
[FBS - 36] (https://dsd-fdte.atlassian.net/browse/FBS-36?atlOrigin=eyJpIjoiZDgzZjg4ZGRmNjZmNGMwMmJmZGQ5OGIxNDdhMzM3NTAiLCJwIjoiaiJ9)

2022-08-26 21:19 UTC, elsonfojr-fdte requested changes

2022-08-26 21:19 UTC, elsonfojr-fdte commented on src/pages/dashboard/dashboard.tsx
> +        </S.Frame>
O frame não pode estar aqui pois ele conflita com o outlet. Fica sobrepondo quando navega

2022-09-02 18:57 UTC, gabrielacsalesc commented on src/pages/dashboard/dashboard.tsx
> +        </S.Frame>
Resolvido. Foi criado uma nova página com o dashboardo do metabase e criada uma nova rota para acessá-lo. Assim como um ícone no sidebar para ir diretamente para o dashboard.

2022-09-02 19:44 UTC, elsonfojr-fdte approved these changes

2022-09-02 19:44 UTC, merged